version: "3.7"
services:
  react-imf:
    container_name: react-imf
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - 3001:3000
    environment:
      CHOKIDAR_USEPOLLING: true
    stdin_open: true
    networks:
      - bridge

networks:
  bridge:
    driver: bridge
