version: "3.7"
services:
    react-imf:
        container_name: react-imf
        build:
            context: .
            dockerfile: Dockerfile
        stdin_open: true
        ports:
            - 3000:3000
        environment:
            - TZ=America/Denver
            - CHOKIDAR_USEPOLLING=true
            - REACT_APP_IMF_MOCK=1
        volumes:
            - .:/app
